# Generated by Django 4.2.4 on 2023-08-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(default='답변 대기', max_length=10),
        ),
    ]
