# Generated by Django 4.2.3 on 2023-08-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_change_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='change_image',
        ),
    ]
